### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by uspi** [BogDAAAMN/deta-deploy-action#1]
With a new push, stage `Set up job` and `Run actions/checkout@v2` go well, but at stage `Run BogDAAAMN/deta-deploy-action@v1.0.0` an error occurs:
```
with:
    deta-access-token: ***
    deta-name: server-one
    deta-project: default
#=#=#                                                                         

######################################################################## 100.0%
                                                                           0.0%
#######################################                                   54.5%
########################################################                  78.9%
######################################################################## 100.0%
Archive:  /home/runner/.deta/bin/deta.zip
  inflating: deta                    
Deta was installed successfully to /home/runner/.deta/bin/deta
Manually add /home/runner/.deta/bin/deta to your path:
  export PATH="/home/runner/.deta/bin:$PATH"
 
  Run '/home/runner/.deta/bin/deta --help' to get started
Error: failed to list spaces: Unauthorized
Error: Process completed with exit code 1.
```
My actions:
On deta: added a new key in settings by pressing button `Create Key`.
Copied the key value and added the repository with code `DETA_TOKEN` to the secrets.
Created an action file.
[My action file](https://gist.github.com/uspi/7b3906e0919fe6a2043b07b954c0c226)

**Comment by bogdaaamn** [comment]
Hey @uspi! 

> My actions:
> On deta: added a new key in settings by pressing button `Create Key`.
> Copied the key value and added the repository with code `DETA_TOKEN` to the secrets.

You generated and used the `API key` for the project, that serves other purposes than the `access tokens` (see https://docs.deta.sh/docs/micros/api_keys). You need to generate an `access token` from your profile settings page and add it to the `DETA_TOKEN` secret and in your action file instead.

> The deta cli also authenticates with deta access tokens. You can create an access token under the `Settings` view at `https://web.deta.sh/home/:your_username/` (also accessible by clicking the blue left caret `<` from the nav bar in a project's view). The access tokens are **valid for a year**.

from https://docs.deta.sh/docs/cli/auth#deta-access-tokens

**Comment by uspi** [comment]
It works, thanks!
