### ISSUE TITLE
[Question] Does it auto deploy on push?

### ISSUE THREAD

**Issue by max-programming** [BogDAAAMN/deta-deploy-action#8]
I just have a simple question that does this GH action automatically deploy whenever a push is made? Something like Netlify and Vercel?

**Comment by bogdaaamn** [comment]
Hey @max-programming, yes exactly, you can achieve that with GitHub Actions. The example is running on push, for example.

https://github.com/BogDAAAMN/deta-deploy-action/blob/829079c735ba8b7a5368a8d11b37162fee428179/README.md?plain=1#L50

But you can do many other combinations and triggers if you want to achieve something else (like selecting branches or pull requests or anything). You can check out [Workflow syntax for GitHub Actions – GitHub Docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on).

**Comment by max-programming** [comment]
Thanks for the reply!
